// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var $accordionLink, $link;
    $(document).foundation({
      accordion: {
        toggleable: false
      }
    });
    $('.orbit-bullets-container').addClass('row');
    $accordionLink = $('.accordion__link');
    $accordionLink.click(function() {
      $accordionLink.addClass('accordion__link--inactive');
      return $(this).removeClass('accordion__link--inactive');
    });
    $link = $('.header-sub__nav-link');
    return $link.click(function() {
      $(this).parent().toggleClass('header-sub__nav-item--active');
      return $(this).toggleClass('header-sub__nav-link--active');
    });
  });

}).call(this);
