// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var $link;
    $(document).foundation();
    $('.orbit-bullets-container').addClass('row');
    $link = $('.header-sub__nav-link');
    return $link.click(function() {
      $(this).parent().toggleClass('header-sub__nav-item--active');
      return $(this).toggleClass('header-sub__nav-link--active');
    });
  });

}).call(this);
