// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var $link;
    $link = $('.header-sub__nav-link');
    $link.click(function() {
      $(this).parent().toggleClass('header-sub__nav-item--active');
      return $(this).toggleClass('header-sub__nav-link--active');
    });
    return $(document).foundation();
  });

}).call(this);
